// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $api_joke from "./routes/api/joke.ts";
import * as $consent from "./routes/consent.tsx";
import * as $flow_examples from "./routes/flow-examples.tsx";
import * as $greet_name_ from "./routes/greet/[name].tsx";
import * as $health_alive from "./routes/health/alive.ts";
import * as $health_ready from "./routes/health/ready.ts";
import * as $index from "./routes/index.tsx";
import * as $login from "./routes/login.tsx";
import * as $logout from "./routes/logout.tsx";
import * as $recovery from "./routes/recovery.tsx";
import * as $registration from "./routes/registration.tsx";
import * as $sessions from "./routes/sessions.tsx";
import * as $settings from "./routes/settings.tsx";
import * as $verification from "./routes/verification.tsx";
import * as $BasicUI from "./islands/BasicUI.tsx";
import * as $UIForm from "./islands/UIForm.tsx";
import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/api/joke.ts": $api_joke,
    "./routes/consent.tsx": $consent,
    "./routes/flow-examples.tsx": $flow_examples,
    "./routes/greet/[name].tsx": $greet_name_,
    "./routes/health/alive.ts": $health_alive,
    "./routes/health/ready.ts": $health_ready,
    "./routes/index.tsx": $index,
    "./routes/login.tsx": $login,
    "./routes/logout.tsx": $logout,
    "./routes/recovery.tsx": $recovery,
    "./routes/registration.tsx": $registration,
    "./routes/sessions.tsx": $sessions,
    "./routes/settings.tsx": $settings,
    "./routes/verification.tsx": $verification,
  },
  islands: {
    "./islands/BasicUI.tsx": $BasicUI,
    "./islands/UIForm.tsx": $UIForm,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
